In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def data_maker(n_sample, std_, mean_len, mean_wid):
    N = n_sample
    std = std_

    bananas_width = np.random.normal(mean_wid[0], std, N)
    apples_width = np.random.normal(mean_wid[1], std, N)

    bananas_length = np.random.normal(mean_len[0], std, N)
    apples_length = np.random.normal(mean_len[1], std, N)

    width = np.concatenate((bananas_width, apples_width))
    length = np.concatenate((bananas_length, apples_length))

    X = np.array([width, length]).T

    bananas_label = np.zeros(N, dtype='int')
    apples_labels = np.ones(N, dtype='int')

    Y = np.concatenate((bananas_label, apples_labels))
    return X, Y

In [3]:
class KNearestNeighbors:
    def __init__(self, k):
        self.k = k
    
    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train
        self.number_classes = len(np.unique(y_train))
    
    def nearNeighbors(self, x_test):
        distance = np.sqrt(np.sum((x_test - self.X_train)**2, axis=1))
        near_neighbors = np.argsort(distance)[0:self.k]
        return near_neighbors
    
    def predict(self, x_test):
        near_neighbors = self.nearNeighbors(x_test)
        print(near_neighbors)
        y = np.argmax(np.bincount(self.y_train[near_neighbors]))
        return y
    
    def evaluate(self, x, y):
        pred_list = []
        for item in x:
            pred_list.append(self.predict(item))
        score = np.sum(y == np.array(pred_list))
        return score

In [4]:
knn = KNearestNeighbors(k=5)
X, Y = data_maker(100, 0.6, (8,6), (4,6))
knn.fit(X, Y)

In [5]:
mive_jadid = np.array([4.7, 6.8])
y_pred = knn.predict(mive_jadid)
print(y_pred)

[120 176 143  93 158]
1


In [6]:
X1, Y1 = data_maker(50, 0.3, (8,6), (4,6))
score1 = knn.evaluate(X1, Y1)
print(score1)

[13 86 90  5 66]
[83 47 98  9 90]
[43 31 40 58  4]
[ 9 90 86 13 66]
[28  6 17 34  5]
[53  6 34 85 66]
[96 32 52 57 41]
[27 82 84 78 17]
[43 58 31 59  4]
[85 91 51 53 61]
[39 14 77 37 30]
[84 27 94 82 78]
[40 43 31 73 76]
[72 49 83 68  9]
[85 62 61 91 53]
[84 94 27 70 82]
[78 46 70 82 27]
[ 1 58  4 24 11]
[ 8 30 34 29 87]
[ 4  1 24 58 61]
[14 39 30 77  8]
[51 30 91  8 85]
[ 1 47 24  4 98]
[61 24  4 51 85]
[61 24  4 58 85]
[24  4 61 58  1]
[ 4 24 58 61  1]
[ 9 90 83 86 47]
[51 91 14 85 76]
[15 73 92 31 43]
[11 23 44 75 63]
[94 84 27 82 60]
[30 51  8 91 14]
[34  8 30 53  6]
[75 67 80 11 23]
[61 24  4 58 85]
[53 91 34 30 85]
[61 85 24 62 91]
[47 62 98 61 24]
[58 59 43  4 44]
[ 3 76 40 73 14]
[24  4 61 58  1]
[53  6 85 91 34]
[90  9 86 13 66]
[ 1 58  4 24 11]
[51 14 30 39 76]
[97 44 92 23 59]
[ 5 17 16 28 13]
[88 25 37 22 77]
[66  6 53  5 85]
[154 189 157 113 168]
[110 189 116 141 105]
[107 174 177 144 139]
[102 107 174 111 106]
[189 110 105 154 116]
[160 154 159 141 129]
[154 125 144 157 1

### Scikit-learn

In [7]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
